### ISSUE TITLE
Trigger error when interactivity request fails

### ISSUE THREAD

**Issue by xavijam** [CartoDB/wax#16]
Related ticket: https://github.com/CartoDB/cartodb.js/issues/1717

When the user reaches its limits, interactivity could be affected, so the idea is to warn CARTO.js about that problem and then it should trigger that error accordingly.

**Comment by nobuti** [comment]
IMO yes, in the same way as tiler limit error, we should check the error is transmitted to cartodb.js. Once we plug the notification, we can check that.

**Comment by rubenmoya** [comment]
Blocked until we merge https://github.com/CartoDB/cartodb/issues/12593

**Comment by rubenmoya** [comment]
Unblocking it!

**Comment by rjimenezda** [comment]
Back to development, this doesn't show the orange tile (specified on the acceptance document)

**Comment by rjimenezda** [comment]
Turns out we won't have to do that, so the reporting from carto.js is fine as it is.

I've been investigating how it behaves when handling the error on builder, and I'm worried about the frequency. It basically fires when changing the hovered tile.

This is because wax has an internal cache for requests, so as soon as it resolves one, it caches the result.

My question is, **is it likely that a user will get this error, but won't get it a few seconds after?** To put it differently, **would it make sense to not cache certain api responses?** Bear in mind, the user has to refresh to clean this cache.

@noguerol @dgaubert

**Comment by matallo** [comment]
while not an ideal situation, the request cache is there for a reason and triggering so many further requests would be killer (in a deadly sense)

so, we can deal with that situation

**Comment by rjimenezda** [comment]
👍 

We'll probably have to debounce the error, but that's easier than messing with the cache system.

**Comment by rubenmoya** [comment]
What should happen when wax throws a limits error? Should we show the error tile? Should we show the map overlay? The infobox in Builder?

cc @noguerol

**Comment by matallo** [comment]
ideally we should show an empty tile in public views (public map, embed, ...)

errors (error tile, infobox, overlay) should only appear in Builder views, let's research how feasible is that @rubenmoya

**Comment by rubenmoya** [comment]
After some discussion what we're doing is:

- Leave the tile as it is since the tile could render and the gridjson fail
- Add infobox in builder with an interactivity error
- No overlay

**Comment by rubenmoya** [comment]
Closing this since we're removing wax

**Comment by xavijam** [comment]
Could you elaborate a bit more your answer @rubenmoya? Replaced by?

**Comment by rubenmoya** [comment]
By a custom implementation as far as I know, I linked the PR in my previous message

**Comment by rubenmoya** [comment]
Reopened! We're not removing wax just yet :joy:
